{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:28:24"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:28:48"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:28:53"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:28:53"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:29:03"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:29:11"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:29:13"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:29:23"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:29:33"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:29:43"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:29:53"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:30:03"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:30:13"}
{"level":"error","message":"Erro na aplicação: Not allowed by CORS","module":"Server","service":"digibot","stack":"Error: Not allowed by CORS\n    at origin (C:\\Users\\athil\\digibot\\backend\\server.js:28:23)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:219:13\n    at optionsCallback (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:199:9)\n    at corsMiddleware (C:\\Users\\athil\\digibot\\backend\\node_modules\\cors\\lib\\index.js:204:7)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:328:13)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:286:9\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at internalNext (C:\\Users\\athil\\digibot\\backend\\node_modules\\helmet\\index.cjs:537:6)","timestamp":"2025-06-18 12:30:23"}
{"errorLabelSet":{},"level":"error","message":"Erro ao carregar comandos: Client must be connected before running operations","module":"BotService","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 14:23:29"}
{"errorLabelSet":{},"level":"error","message":"Erro ao iniciar bot: Client must be connected before running operations","module":"BotService","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 14:23:29"}
{"errorLabelSet":{},"level":"error","message":"Erro ao iniciar bot: Client must be connected before running operations","module":"BotController","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 14:23:29"}
{"errorLabelSet":{},"level":"error","message":"Erro ao carregar comandos: Client must be connected before running operations","module":"BotService","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 22:52:01"}
{"errorLabelSet":{},"level":"error","message":"Erro ao iniciar bot: Client must be connected before running operations","module":"BotService","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 22:52:01"}
{"errorLabelSet":{},"level":"error","message":"Erro ao iniciar bot: Client must be connected before running operations","module":"BotController","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 22:52:01"}
{"level":"error","message":"Erro ao iniciar bot: Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:56:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 22:52:04"}
{"level":"error","message":"Erro ao iniciar bot: Bot já está conectado","module":"BotController","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:56:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 22:52:04"}
{"errorLabelSet":{},"level":"error","message":"Erro ao carregar comandos: Client must be connected before running operations","module":"BotService","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 22:54:09"}
{"errorLabelSet":{},"level":"error","message":"Erro ao iniciar bot: Client must be connected before running operations","module":"BotService","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 22:54:09"}
{"errorLabelSet":{},"level":"error","message":"Erro ao iniciar bot: Client must be connected before running operations","module":"BotController","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-18 22:54:09"}
{"level":"error","message":"Erro ao iniciar bot: MongoDB não está conectado. Aguarde a conexão antes de iniciar o bot.","module":"BotService","service":"digibot","stack":"Error: MongoDB não está conectado. Aguarde a conexão antes de iniciar o bot.\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:65:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:5)","timestamp":"2025-06-18 22:56:42"}
{"level":"error","message":"Erro ao iniciar bot: MongoDB não está conectado. Aguarde a conexão antes de iniciar o bot.","module":"BotController","service":"digibot","stack":"Error: MongoDB não está conectado. Aguarde a conexão antes de iniciar o bot.\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:65:15)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:5)","timestamp":"2025-06-18 22:56:42"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:58:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:08:31"}
{"level":"error","message":"Erro ao iniciar bot: Bot já está conectado","module":"BotController","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:58:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:08:31"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:58:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:15:25"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:58:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:26:06"}
{"0":"C","1":"a","10":"d","11":" ","12":"a","13":"n","14":"o","15":"n","16":"y","17":"m","18":"o","19":"u","2":"n","20":"s","21":" ","22":"m","23":"e","24":"s","25":"s","26":"a","27":"g","28":"e","29":"s","3":"n","30":".","4":"o","5":"t","6":" ","7":"s","8":"e","9":"n","level":"error","message":"Erro ao enviar mensagem de boas-vindas no chat da Twitch:","module":"BotService","service":"digibot","timestamp":"2025-06-18 23:33:27"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:63:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:34:33"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:63:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:36:49"}
{"0":"C","1":"a","10":"d","11":" ","12":"a","13":"n","14":"o","15":"n","16":"y","17":"m","18":"o","19":"u","2":"n","20":"s","21":" ","22":"m","23":"e","24":"s","25":"s","26":"a","27":"g","28":"e","29":"s","3":"n","30":".","4":"o","5":"t","6":" ","7":"s","8":"e","9":"n","level":"error","message":"Erro ao enviar mensagem de boas-vindas no chat da Twitch:","module":"BotService","service":"digibot","timestamp":"2025-06-18 23:37:41"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:63:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:37:59"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:63:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:49:10"}
{"0":"C","1":"a","10":"d","11":" ","12":"a","13":"n","14":"o","15":"n","16":"y","17":"m","18":"o","19":"u","2":"n","20":"s","21":" ","22":"m","23":"e","24":"s","25":"s","26":"a","27":"g","28":"e","29":"s","3":"n","30":".","4":"o","5":"t","6":" ","7":"s","8":"e","9":"n","level":"error","message":"Erro ao enviar mensagem de boas-vindas no chat da Twitch:","module":"BotService","service":"digibot","timestamp":"2025-06-18 23:50:21"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:63:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-18 23:51:25"}
{"0":"C","1":"a","10":"d","11":" ","12":"a","13":"n","14":"o","15":"n","16":"y","17":"m","18":"o","19":"u","2":"n","20":"s","21":" ","22":"m","23":"e","24":"s","25":"s","26":"a","27":"g","28":"e","29":"s","3":"n","30":".","4":"o","5":"t","6":" ","7":"s","8":"e","9":"n","level":"error","message":"Erro ao enviar mensagem de boas-vindas no chat da Twitch:","module":"BotService","service":"digibot","timestamp":"2025-06-18 23:52:21"}
{"0":"C","1":"a","10":"d","11":" ","12":"a","13":"n","14":"o","15":"n","16":"y","17":"m","18":"o","19":"u","2":"n","20":"s","21":" ","22":"m","23":"e","24":"s","25":"s","26":"a","27":"g","28":"e","29":"s","3":"n","30":".","4":"o","5":"t","6":" ","7":"s","8":"e","9":"n","level":"error","message":"Erro ao enviar mensagem de boas-vindas no chat da Twitch:","module":"BotService","service":"digibot","timestamp":"2025-06-18 23:58:12"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:75:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:8:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-19 00:01:40"}
{"0":"C","1":"a","10":"d","11":" ","12":"a","13":"n","14":"o","15":"n","16":"y","17":"m","18":"o","19":"u","2":"n","20":"s","21":" ","22":"m","23":"e","24":"s","25":"s","26":"a","27":"g","28":"e","29":"s","3":"n","30":".","4":"o","5":"t","6":" ","7":"s","8":"e","9":"n","level":"error","message":"Erro ao enviar mensagem de boas-vindas no chat da Twitch:","module":"BotService","service":"digibot","timestamp":"2025-06-19 00:04:20"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:75:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:13:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-19 00:08:05"}
{"errorLabelSet":{},"level":"error","message":"Erro ao listar comandos: Client must be connected before running operations","module":"CommandController","service":"digibot","stack":"MongoNotConnectedError: Client must be connected before running operations\n    at autoConnect (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:95:19)\n    at executeOperation (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\operations\\execute_operation.js:38:40)\n    at FindCursor._initialize (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\find_cursor.js:61:73)\n    at FindCursor.cursorInit (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:633:38)\n    at FindCursor.fetchBatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:667:24)\n    at FindCursor.next (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:347:28)\n    at [Symbol.asyncIterator] (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:255:45)\n    at AsyncGenerator.next (<anonymous>)\n    at FindCursor.toArray (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongodb\\lib\\cursor\\abstract_cursor.js:427:26)\n    at model.Query._find (C:\\Users\\athil\\digibot\\backend\\node_modules\\mongoose\\lib\\query.js:2407:27)","timestamp":"2025-06-19 00:16:52"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:75:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:13:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-19 00:18:32"}
{"level":"error","message":"Erro ao iniciar bot (detalhado): Bot já está conectado","module":"BotService","service":"digibot","stack":"Error: Bot já está conectado\n    at BotService.start (C:\\Users\\athil\\digibot\\backend\\services\\bot.js:75:15)\n    at exports.startBot (C:\\Users\\athil\\digibot\\backend\\controllers\\bot.js:13:22)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:149:13)\n    at Route.dispatch (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\route.js:119:3)\n    at Layer.handle [as handle_request] (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:284:15\n    at Function.process_params (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:346:12)\n    at next (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:280:10)\n    at Function.handle (C:\\Users\\athil\\digibot\\backend\\node_modules\\express\\lib\\router\\index.js:175:3)","timestamp":"2025-06-19 00:18:47"}
